@startuml
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define primary_key(x) <u>x</u>
hide methods
hide stereotypes

' -- Enumerations --
enum OrderStatus {
   PENDING
   IN_PROGRESS
   COMPLETED
   CANCELED
}

enum PaymentStatus {
   UNPAID
   PAID
   REFUNDED
}

enum TransactionStatus {
   SUCCESSFUL
   FAILED
   PENDING
}

enum PaymentMethod {
   CARD
   APPLE_PAY
   GOOGLE_PAY
}

enum Category {
   APPETIZER
   ENTREE
   DESSERT
}

' -- Classes --
abstract class User {
   +{field} String uniqueIdentifier
   +String name
   +String phoneNumber
   +String email
}

class Restaurant {
   +String location
   +Menu menu
}

class Diner {
   +String dietaryPreferences
   +List<PaymentMethod> paymentMethods
}

class Menu {
   +List<MenuItem> items
}

class MenuItem {
   +String uniqueIdentifier
   +String name
   +String ingredients
   +String dietarySpecifications
   +Category category
   +Double price
   +Boolean isAvailable
}

class Order {
   +String uniqueIdentifier
   +List<MenuItem> items
   +DateTime timestamp
   +String tableNumber
   +OrderStatus orderStatus
   +PaymentStatus paymentStatus
}

class Payment {
   +Double amount
   +PaymentMethod paymentMethod
   +TransactionStatus transactionStatus
}

' -- Relationships --
User <|-- Restaurant : Inheritance
User <|-- Diner : Inheritance
Restaurant "1" *-- "1" Menu : has
Menu "1" *-- "*" MenuItem : contains
Diner "1" *-- "*" Order : places
Order "*" -- "*" MenuItem : includes
Order "1" *-- "1" Payment : initiates
@enduml